build]
  base = "."  # Set base to root directory since your frontend is in the repo root
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

# Redirect API calls to Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://pokemon-tcg-dashboard-production.up.railway.app/api/:splat"
  status = 200
  force = true

# SPA fallback - redirect all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200